Repository dnsimple/dnsimple-ruby, pull requests merged in 2021-04, with the labels that each got.

#231 Drop the inexistent domain#reset_domain_token method
  CHANGELOG.md
  lib/dnsimple/client/domains.rb
  spec/dnsimple/client/domains_spec.rb
  spec/fixtures.http/resetDomainToken/success.http
Labels: enhancement, ready-for-review, requires-major-release

#230 Implement registrar methods for Domain Prices API
  CHANGELOG.md
  lib/dnsimple/client/registrar.rb
  lib/dnsimple/struct.rb
  lib/dnsimple/struct/domain_price.rb
  spec/dnsimple/client/registrar_spec.rb
  spec/fixtures.http/getDomainPrices/failure.http
  spec/fixtures.http/getDomainPrices/success.http
Labels: enhancement, ready-for-review

#232 Remove deprecated expires_on attributes
  CHANGELOG.md
  lib/dnsimple/struct/certificate.rb
  lib/dnsimple/struct/domain.rb
  spec/dnsimple/client/certificates_spec.rb
  spec/dnsimple/client/domains_spec.rb
Labels: enhancement, ready-for-review, requires-major-release

#234 Update to RuboCop v1.13.0
  .rubocop.yml
  .rubocop_todo.yml
  .travis.yml
  CHANGELOG.md
  Gemfile
  dnsimple.gemspec
  lib/dnsimple/client/clients.rb
  lib/dnsimple/error.rb
  lib/dnsimple/extra.rb
  spec/dnsimple/client/domains_collaborators_spec.rb
  spec/dnsimple/client_spec.rb
  spec/dnsimple/options/list_options_spec.rb
  spec/spec_helper.rb
Labels: dependencies, enhancement, ready-for-review
